/**
 * @author baihu868
 * INFO202 2019
 * ProductEditor.java
 */
package gui;

import dao.DAOException;
import dao.DaoInterface;
import dao.ProductDatabase;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import net.sf.oval.*;
import net.sf.oval.exception.*;

public class ProductEditor extends javax.swing.JDialog {
    DaoInterface pd;
    SimpleListModel slm = new SimpleListModel();
    
    /**
     * Creates new form ProductEditor
     * @param parent
     */
    public ProductEditor(java.awt.Frame parent, boolean modal, DaoInterface di) {
        super(parent, modal);
        initComponents();
        this.pd = di;
        comboCategory.setEditable(true);
        slm.updateItems(pd.returnCategories());
        comboCategory.setModel(slm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescription = new javax.swing.JTextArea();
        labelDescription = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        labelQuantityinStock = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtQuantityInStock = new javax.swing.JTextField();
        productSaveButton = new javax.swing.JButton();
        productCancelButton = new javax.swing.JButton();
        comboCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelID.setText("Product ID");

        txtID.setName("txtID"); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        labelName.setText("Product Name");

        txtName.setName("txtName"); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtareaDescription.setColumns(20);
        txtareaDescription.setRows(5);
        txtareaDescription.setName("txtareaDescription"); // NOI18N
        jScrollPane1.setViewportView(txtareaDescription);

        labelDescription.setText("Description");

        labelCategory.setText("Category");

        labelPrice.setText("Price");

        labelQuantityinStock.setText("Quantity in stock");

        txtPrice.setName("txtPrice"); // NOI18N

        txtQuantityInStock.setName("txtQuantityInStock"); // NOI18N

        productSaveButton.setText("Save");
        productSaveButton.setName("productSaveButton"); // NOI18N
        productSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSaveButtonActionPerformed(evt);
            }
        });

        productCancelButton.setText("Cancel");
        productCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCancelButtonActionPerformed(evt);
            }
        });

        comboCategory.setName("comboCategory"); // NOI18N
        comboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(productCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelQuantityinStock, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantityInStock)
                    .addComponent(txtPrice)
                    .addComponent(comboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(labelDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategory)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantityinStock)
                    .addComponent(txtQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSaveButton)
                    .addComponent(productCancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void productSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSaveButtonActionPerformed
        try{
            String id = txtID.getText();   
            String name = txtName.getText();
            String description = txtareaDescription.getText();
            String category = (String) comboCategory.getSelectedItem();
            BigDecimal price = new BigDecimal(txtPrice.getText());
            BigDecimal quantity = new BigDecimal(txtQuantityInStock.getText());
        
            Product product = new Product(id, name, description, category, price, quantity);
            System.out.println(product.toString());
            new Validator().assertValid(product);
            pd.saveProduct(product);
            dispose();
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,
            "You have entered a price or quantity that is not a valid number.",
            "Input Error", JOptionPane.ERROR_MESSAGE);
        }catch(ConstraintsViolatedException ex){
            // get the violated constraints from the exception
            ConstraintViolation[] violations = ex.getConstraintViolations();
            // create a nice error message for the user
            String msg = "Please fix the following input problems:";
            for (ConstraintViolation cv : violations) {
            msg += "\n •" + cv.getMessage();
            }
            // display the message to the user
            JOptionPane.showMessageDialog(this, msg, "Input Error",
            JOptionPane.ERROR_MESSAGE);       
        }catch(DAOException ex){
            String msg;
            msg = ex.getMessage();
            JOptionPane.showMessageDialog(this, msg,
            "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_productSaveButtonActionPerformed

    private void productCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_productCancelButtonActionPerformed

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
    
    }//GEN-LAST:event_comboCategoryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Product> comboCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQuantityinStock;
    private javax.swing.JButton productCancelButton;
    private javax.swing.JButton productSaveButton;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantityInStock;
    private javax.swing.JTextArea txtareaDescription;
    // End of variables declaration//GEN-END:variables
}
