/**
 * @author baihu868
 * INFO202 2019
 * ProductViewer
 */
package gui;

import dao.DaoInterface;
import dao.ProductDatabase;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.util.Collection;

public class ProductViewer extends javax.swing.JDialog {
    final DaoInterface pd = new ProductDatabase();
    Collection<Product> allProducts = pd.returnProducts();
    SimpleListModel productSLM = new SimpleListModel();
    SimpleListModel categorySLM = new SimpleListModel();
    
    /**
     * Creates new form ProductViewer
     * @param parent
     * @param modal
     * @param di
     */
    public ProductViewer(java.awt.Frame parent, boolean modal, DaoInterface di) {
        super(parent, modal);
        initComponents();
        productSLM.updateItems(pd.returnProducts());
        viewerList.setModel(productSLM);
        categorySLM.updateItems(pd.returnCategories());
        viewerCategoryBox.setModel(categorySLM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewerOptionpane = new javax.swing.JOptionPane();
        viewerScrollpane = new javax.swing.JScrollPane();
        viewerList = new javax.swing.JList<>();
        viewerClose = new javax.swing.JButton();
        viewerDelete = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        viewerSearchButton = new javax.swing.JButton();
        viewerCategoryBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        viewerScrollpane.setViewportView(viewerList);

        viewerClose.setText("Close");
        viewerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerCloseActionPerformed(evt);
            }
        });

        viewerDelete.setText("Delete");
        viewerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerDeleteActionPerformed(evt);
            }
        });

        viewerSearchButton.setText("Search");
        viewerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerSearchButtonActionPerformed(evt);
            }
        });

        viewerCategoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewerCategoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerCategoryBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewerScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewerCategoryBox, 0, 347, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(viewerSearchButton)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewerClose)
                        .addGap(66, 66, 66)
                        .addComponent(viewerDelete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewerSearchButton))
                .addGap(19, 19, 19)
                .addComponent(viewerCategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewerScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewerDelete)
                    .addComponent(viewerClose))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerCloseActionPerformed
        dispose();
    }//GEN-LAST:event_viewerCloseActionPerformed

    private void viewerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerDeleteActionPerformed
        if(viewerList.isSelectionEmpty() == (false)){
            Product product = viewerList.getSelectedValue();     
            int result = viewerOptionpane.showConfirmDialog(this, "Confirm deletion");
            if (result == viewerOptionpane.YES_OPTION) {
                pd.removeProduct(product);
                productSLM.updateItems(pd.returnProducts());
            }
        }
    }//GEN-LAST:event_viewerDeleteActionPerformed

    private void viewerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerSearchButtonActionPerformed
        String productID = searchBar.getText();
        productSLM.updateItems(pd.searchProducts(productID));
    }//GEN-LAST:event_viewerSearchButtonActionPerformed

    private void viewerCategoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerCategoryBoxActionPerformed
        if("All".equals((String)viewerCategoryBox.getSelectedItem())){
            viewerList.setModel(productSLM);
            productSLM.updateItems(pd.returnProducts());
        }else{
            productSLM.updateItems(pd.returnCategoryProducts((String) viewerCategoryBox.getSelectedItem()));
            viewerList.setModel(productSLM);
        }
    }//GEN-LAST:event_viewerCategoryBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchBar;
    private javax.swing.JComboBox<String> viewerCategoryBox;
    private javax.swing.JButton viewerClose;
    private javax.swing.JButton viewerDelete;
    private javax.swing.JList<Product> viewerList;
    private javax.swing.JOptionPane viewerOptionpane;
    private javax.swing.JScrollPane viewerScrollpane;
    private javax.swing.JButton viewerSearchButton;
    // End of variables declaration//GEN-END:variables
}
